name: typo3-inst
type: typo3
docroot: public
project_tld: localhost
additional_hostnames:
  - api.typo3-inst
php_version: "8.4"
webserver_type: nginx-fpm
database:
  type: mariadb
  version: "10.11"
composer_version: "2"
web_environment:
  - TYPO3_CONTEXT=Development
  - NODE_OPTIONS=--max-old-space-size=2048
  - TYPO3_SITE_BASE=https://api.typo3-inst.localhost/
  - TYPO3_BACKEND_BASE=https://api.typo3-inst.localhost/
  - TYPO3_FRONTEND_BASE=https://typo3-inst.localhost/
nodejs_version: "22"
# web_extra_daemons:
#   - name: nextjs
#     command: "yarn start"
#     directory: /var/www/html/frontend
web_extra_daemons:
  - name: nextjs
    command: "bash -c 'cd /var/www/html/frontend && corepack enable && corepack prepare yarn@4.12.0 --activate && yarn install --frozen-lockfile && yarn dev'"
    directory: /var/www/html/frontend
