jobs:
  javascript-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          cd typo3-dev/packages/pixelcoda_search
          yarn install --check-files
      - name: Run ESLint
        run: |
          cd typo3-dev/packages/pixelcoda_search
          yarn lint --verbose
