base: '%env(TYPO3_SITE_BASE)%'
customConfiguration:
  renderingMode: headless
dependencies:
  - typo3/fluid-styled-content
  - friendsoftypo3/headless
  - pixelcoda/sitepackage
  - pixelcoda/fe-editor
  - pixelcoda/typo3-search
frontendBase: '%env(TYPO3_FRONTEND_BASE)%'
headless: 1
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    frontendBase: '%env(TYPO3_FRONTEND_BASE)%'
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      .json: 834
  PixelcodaSearch:
    type: Simple
    routePath: /suche
    _arguments:
      q: q
      collections: collections
websiteTitle: ''
