base: 'https://api.typo3-inst.localhost/'
customConfiguration:
  renderingMode: headless
dependencies:
  - typo3/fluid-styled-content
  - friendsoftypo3/headless
  - friendsoftypo3/headless-mixed
frontendBase: 'https://typo3-inst.localhost/'
headless: 1
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 2
websiteTitle: ''
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      .json: 834
  PixelcodaSearch:
    type: Simple
    limitToPages: [2]
    routePath: '/suche'
    _arguments:
      q: 'q'
      collections: 'collections'
